triotech_adminer_home:
  path: /
  defaults:
    _controller: 'Triotech\AdminerBundle\Controller\ProxyController::proxyAction'

triotech_adminer_css:
  path: /{type}/{asset}
  defaults:
    _controller: 'Triotech\AdminerBundle\Controller\ProxyController::assetAction'
