services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Triotech\AdminerBundle\Adminer\DatabaseExtractor:
        class: Triotech\AdminerBundle\Adminer\DatabaseExtractor
        arguments:
            - "@doctrine"
            - "%triotech.adminer_path%"
