services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $adminerPath: "%triotech.adminer_path%"

  Triotech\AdminerBundle\Adminer\DatabaseExtractor:
  Triotech\AdminerBundle\Controller\ProxyController:

  Triotech\AdminerBundle\DataCollector\ProfilerIcon:
    tags:
    - name: data_collector
      template: "@TriotechAdminer/profiler_toolbar_link.html.twig"
      id: "profiler_adminer_icon"

  Triotech\AdminerBundle\Twig\TwigExtension:
    tags:
    - name: twig.extension
