services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Triotech\AdminerBundle\Adminer\DatabaseExtractor:
        public: true
        class: Triotech\AdminerBundle\Adminer\DatabaseExtractor
        arguments:
            - "@doctrine"
            - "%triotech.adminer_path%"

    Triotech\AdminerBundle\DataCollector\ProfilerIcon:
        class: Triotech\AdminerBundle\DataCollector\ProfilerIcon
        tags:
            - { name: data_collector, template: "@TriotechAdminer/profiler_toolbar_link.html.twig", id: "profiler_adminer_icon" }
